---
- name: Run the proxyservices.certificates.letsencrypt role.
  hosts: '{{ target | default("letsencrypt") }}'
  roles:
    - { role: proxyservices.certificates.letsencrypt, tags: ['certificates', 'letsencrypt']}

...
